### ISSUE TITLE
Error: (HTTP code 400) unexpected - Invalid reference format

### ISSUE THREAD

**Issue by alexgarciavila** [MichelFR/MqDockerUp#258]
Good afternoon,

I've encountered an issue when attempting to start the Docker container in my environment. After initiating the container, it automatically restarts after a few seconds due to an error. This is causing inconvenience in the proper functioning of the MQTT service in my Home Assistant instance.

MqDockerUp restarts and does not function correctly, thereby preventing the MQTT service from receiving data from all containers as it should.

I have attached a screenshot showing the specific error I am experiencing.

Any help or suggestions to resolve this issue would be greatly appreciated!

![20240312-7289](https://github.com/MichelFR/MqDockerUp/assets/55148944/f08d0e26-a0cb-49f1-b2fc-b8432bf22b18)

Thanks you for your assistance!

**Comment by alexgarciavila** [comment]
Same problem with release 1.9.0

**Comment by dfrazao** [comment]
Same issue here

**Comment by marleyjaffe** [comment]
Interestingly, mine also provides a 400 error directly after checking the Immich containers. Could that be part of the issue?

```
17.12.2024 02:51:47 [warn] Failed to find new digest for image ghcr.io/immich-app/immich-server:release
17.12.2024 02:51:47 [error] MqDockerUp stopped due to an error
17.12.2024 02:51:47 [error] object
17.12.2024 02:51:47 [error] Error: (HTTP code 400) unexpected - invalid reference format 
    at /app/node_modules/docker-modem/lib/modem.js:382:17
    at getCause (/app/node_modules/docker-modem/lib/modem.js:417:7)
    at Modem.buildPayload (/app/node_modules/docker-modem/lib/modem.js:378:5)
    at IncomingMessage.<anonymous> (/app/node_modules/docker-modem/lib/modem.js:346:16)
    at IncomingMessage.emit (node:events:529:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
12/16/2024 06:51:47 PM Container stopped
```

**Comment by mike391** [comment]
this happens on all immich containers and ddns updater as well.  This script should really fail gracefully (try/catch) and just skip over entries that have these errors. Ill have to look into it and open an MR to avoid the crashes at least.

**Comment by koostamas** [comment]
Happening to me as well. Any updates?

**Comment by gustakasn0v** [comment]
> Interestingly, mine also provides a 400 error directly after checking the Immich containers. Could that be part of the issue?
> 
> ```
> 17.12.2024 02:51:47 [warn] Failed to find new digest for image ghcr.io/immich-app/immich-server:release
> 17.12.2024 02:51:47 [error] MqDockerUp stopped due to an error
> 17.12.2024 02:51:47 [error] object
> 17.12.2024 02:51:47 [error] Error: (HTTP code 400) unexpected - invalid reference format 
>     at /app/node_modules/docker-modem/lib/modem.js:382:17
>     at getCause (/app/node_modules/docker-modem/lib/modem.js:417:7)
>     at Modem.buildPayload (/app/node_modules/docker-modem/lib/modem.js:378:5)
>     at IncomingMessage.<anonymous> (/app/node_modules/docker-modem/lib/modem.js:346:16)
>     at IncomingMessage.emit (node:events:529:35)
>     at IncomingMessage.emit (node:domain:489:12)
>     at endReadableNT (node:internal/streams/readable:1400:12)
>     at processTicksAndRejections (node:internal/process/task_queues:82:21)
> 12/16/2024 06:51:47 PM Container stopped
> ```
> @marleyjaffe 

Thanks for pointing this out. In my case it was crashing even before logging which container was being inspected, which made debugging painful. I've added https://github.com/MichelFR/MqDockerUp/pull/643 to help with that, now we should be able to see `Inspecting container XYZ` in the logs before a crash

Heads-up, MqDockerUp currently crashes _at least_ with all immich images, ie. from https://docs.immich.app/install/docker-compose. I think it's because MqDockerUp doesn't inspect the `.env` file that Immich uses, rendering `ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}` unreadable.

**Comment by radsonpatrick** [comment]
i have this problem 

```2.07.2026 12:39:38 [info] Found source repository: https://github.com/linuxserver/docker-plex

22.07.2026 12:39:38 [debug] exec_create: /bin/sh -c wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1: seerr

22.07.2026 12:39:38 [debug] exec_start: /bin/sh -c wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1: seerr

22.07.2026 12:39:38 [debug] exec_die: seerr

22.07.2026 12:39:38 [info] Image dockurr/samba:latest is up-to-dateFailed to find new digest for image ghcr.io/seerr-team/seerr:latestFailed to find new digest for image ghcr.io/seerr-team/seerr:latestFailed to find new digest for image ghcr.io/seerr-team/seerr:latest

22.07.2026 12:39:38 [info] Found source repository: https://github.com/dockur/samba

22.07.2026 12:39:38 [info] New version available for image lscr.io/linuxserver/code-server:latest

22.07.2026 12:39:38 [info] Found source repository: https://github.com/linuxserver/docker-code-server

22.07.2026 12:39:38 [info] New version available for image nginx:alpineFailed to find new digest for image ghcr.io/seerr-team/seerr:latestFailed to find new digest for image ghcr.io/seerr-team/seerr:latest

22.07.2026 12:39:39 [warn] Could not find source repository for nginx

22.07.2026 12:39:39 [error] Github access token is not defined

22.07.2026 12:39:39 [warn] Failed to find new digest for image ghcr.io/seerr-team/seerr:latest

22.07.2026 12:39:39 [info] Shutting down MqDockerUp...

22.07.2026 12:39:39 [info] Closing MQTT connection...

22.07.2026 12:39:39 [info] MQTT connection closed successfully

22.07.2026 12:39:39 [error] MqDockerUp stopped due to an error

22.07.2026 12:39:39 [error] object

22.07.2026 12:39:39 [error] Error: (HTTP code 404) no such image - No such image: lscr.io/linuxserver/orcaslicer:latest 

    at /app/node_modules/docker-modem/lib/modem.js:389:17

    at getCause (/app/node_modules/docker-modem/lib/modem.js:424:7)

    at Modem.buildPayload (/app/node_modules/docker-modem/lib/modem.js:385:5)

    at IncomingMessage.<anonymous> (/app/node_modules/docker-modem/lib/modem.js:353:16)

    at IncomingMessage.emit (node:events:521:24)

    at IncomingMessage.emit (node:domain:489:12)

    at endReadableNT (node:internal/streams/readable:1735:12)

    at processTicksAndRejections (node:internal/process/task_queues:90:21)

> mqdockerup@2.0.0 start

> ts-node src/index.ts

22.07.2026 12:40:33 [infoFailed to find new digest for image ghcr.io/home-assistant/home-assistant:beta] 

  __  __       ____             _             _   _       

 |  \/  | __ _|  _ \  ___   ___| | _____ _ __| | | |_ __  

 | |\/| |/ _` | | | |/ _ \ / __| |/ / _ \ '__| | | | '_ \ 

 | |  | | (_| | |_| | (_) | (__|   <  __/ |  | |_| | |_) |

 |_|  |_|\__, |____/ \___/ \___|_|\_\___|_|   \___/| .__/ 

            |_|                                    |_|    

Starting MqDockerUp V2.0.0 ... 

22.07.2026 12:40:33 [infoFailed to find new digest for image ghcr.io/seerr-team/seerr:latest] Connected to the database.

22.07.2026 12:40:33 [info] Database initialized successfully

22.07.2026 12:40:34 [info] MQTT client successfully connected

22.07.2026 12:40:34 [info] Checking for removed containers...

22.07.2026 12:40:34 [info] Checking for containers...

22.07.2026 12:40:34 [debug] Ignoring MqDockerUp container updates for micrib/mqdockerup:latest

22.07.2026 12:40:34 [info] Finished checking for containers

22.07.2026 12:40:34 [info] Next check in 5 minutesFailed to find new digest for image ghcr.io/seerr-team/seerr:latest

22.07.2026 12:40:34 [verbose] Setting up startContainerCheckingInterval with value 5m

22.07.2026 12:40:34 [info] Checking for image updates...

22.07.2026 12:40:34 [debug] Ignoring MqDockerUp container updates for micrib/mqdockerup:latest

22.07.2026 12:40:34 [info] Image indifferentbroccoli/projectzomboid-server-docker:latest is up-to-date

22.07.2026 12:40:34 [warn] Could not find source repository for indifferentbroccoli/projectzomboid-server-docker

22.07.2026 12:40:34 [info] New version available for image lscr.io/linuxserver/radarr:latest

22.07.2026 12:40:34 [info] Found source repository: https://github.com/linuxserver/docker-radarr

22.07.2026 12:40:35 [info] New version available for image lscr.io/linuxserver/prowlarr:latest

22.07.2026 12:40:35 [info] Found source repository: https://github.com/linuxserver/docker-prowlarr

22.07.2026 12:40:35 [info] New version available for image mysql:8

22.07.2026 12:40:35 [warn] Could not find source repository for mysql

22.07.2026 12:40:35 [info] New version available for image mysql:8.4

22.07.2026 12:40:35 [warn] Could not find source repository for mysql

22.07.2026 12:40:35 [info] New version available for image traefik:latest

22.07.2026 12:40:35 [info] Found source repository: https://github.com/traefik/traefik

22.07.2026 12:40:36 [info] New version available for image esphome/esphome:latest

22.07.2026 12:40:36 [info] Found source repository: https://github.com/esphome/esphome

22.07.2026 12:40:36 [error] Github access token is not defined

22.07.2026 12:40:36 [warn] Failed to find new digest for image ghcr.io/home-assistant/home-assistant:beta

22.07.2026 12:40:36 [info] Image pihole/pihole:latest is up-to-date

22.07.2026 12:40:36 [info] Found source repository: https://github.com/pi-hole/docker-pi-hole

22.07.2026 12:40:36 [info] New version available for image lscr.io/linuxserver/plex:latest

22.07.2026 12:40:36 [info] Found source repository: https://github.com/linuxserver/docker-plex

22.07.2026 12:40:36 [info] Image dockurr/samba:latest is up-to-date

22.07.2026 12:40:36 [info] Found source repository: https://github.com/dockur/samba

22.07.2026 12:40:36 [info] New version available for image lscr.io/linuxserver/code-server:latest

22.07.2026 12:40:36 [info] Found source repository: https://github.com/linuxserver/docker-code-serverFailed to find new digest for image ghcr.io/seerr-team/seerr:latestFailed to find new digest for image ghcr.io/seerr-team/seerr:latest

22.07.2026 12:40:37 [info] New version available for image nginx:alpine

22.07.2026 12:40:37 [warn] Could not find source repository for nginx

22.07.2026 12:40:37 [error] Github access token is not defined

22.07.2026 12:40:37 [warn] Failed to find new digest for image ghcr.io/seerr-team/seerr:latestFailed to find new digest for image ghcr.io/seerr-team/seerr:latestFailed to find new digest for image ghcr.io/seerr-team/seerr:latest

22.07.2026 12:40:37 [info] Shutting down MqDockerUp...

22.07.2026 12:40:37 [info] Closing MQTT connection...

22.07.2026 12:40:37 [info] MQTT connection closed successfully

22.07.2026 12:40:37 [error] MqDockerUp stopped due to an error

22.07.2026 12:40:37 [error] object

22.07.2026 12:40:37 [error] Error: (HTTP code 404) no such image - No such image: lscr.io/linuxserver/orcaslicer:latest 

    at /app/node_modules/docker-modem/lib/modem.js:389:17

    at getCause (/app/node_modules/docker-modem/lib/modem.js:424:7)

    at Modem.buildPayload (/app/node_modules/docker-modem/lib/modem.js:385:5)

    at IncomingMessage.<anonymous> (/app/node_modules/docker-modem/lib/modem.js:353:16)

    at IncomingMessage.emit (node:events:521:24)

    at IncomingMessage.emit (node:domain:489:12)

    at endReadableNT (node:internal/streams/readable:1735:12)

    at processTicksAndRejections (node:internal/process/task_queues:90:21)

```

**Comment by radsonpatrick** [comment]
I ran into this same crash. MqDockerUp was throwing a fatal error and shutting down completely:

```
Error: (HTTP code 404) no such image - No such image: lscr.io/linuxserver/orcaslicer:latest
    at /app/node_modules/docker-modem/lib/modem.js:389:17
    ...
22.07.2026 12:38:12 [error] MqDockerUp stopped due to an error
```

After digging in, I found the root cause: I had a container (`orcaslicer`) that was in an **`Exited`** state, and its underlying image had since been removed/pruned from Docker. When MqDockerUp tried to inspect/check that container during its update-check cycle, the `docker inspect`/image lookup returned a 404, which wasn't handled gracefully — it just killed the whole process instead of skipping that container and continuing with the rest.

**Steps to reproduce:**
1. Have a container that is stopped (`Exited`) and whose image no longer exists locally (e.g. was pruned with `docker image prune`).
2. Start/restart MqDockerUp.
3. It crashes with a 404 "no such image" error and shuts down entirely instead of just logging a warning and skipping that container.

**Workaround:** I removed the exited `orcaslicer` container (`docker rm -f orcaslicer`), and MqDockerUp started working normally again.

**Suggestion:** It would be great if MqDockerUp could catch this 404 case per-container and just log a warning/skip it, rather than letting it bubble up and stop the entire app. This would make it more resilient when someone has stale/exited containers with missing images lying around.
