### ISSUE TITLE
mqdockerup stops after image is pulled

### ISSUE THREAD

**Issue by JackTalisker** [MichelFR/MqDockerUp#404]
mqdockerup stops after image is pulled without build container (I have to build it by myself)
Here is the mqdockerup container log:

```
2024-12-04T18:10:36.357673864Z 04.12.2024 18:10:36 [info] New version available for image lscr.io/linuxserver/duplicati:latest
2024-12-04T18:10:36.588961853Z 04.12.2024 18:10:36 [info] Image ghcr.io/qdm12/ddns-updater:latest is up-to-date
2024-12-04T18:10:36.946469816Z 04.12.2024 18:10:36 [info] Image micrib/mqdockerup:latest is up-to-date
2024-12-04T18:10:37.294436416Z 04.12.2024 18:10:37 [info] Image tsightler/ring-mqtt:latest is up-to-date
2024-12-04T18:10:37.526330170Z 04.12.2024 18:10:37 [info] Image ghcr.io/home-assistant/home-assistant:stable is up-to-date
2024-12-04T18:10:37.868372121Z 04.12.2024 18:10:37 [info] Image cloudflare/cloudflared:latest is up-to-date
2024-12-04T18:10:38.206034051Z 04.12.2024 18:10:38 [info] Image eclipse-mosquitto:latest is up-to-date
2024-12-04T18:10:38.549231515Z 04.12.2024 18:10:38 [info] Image instantlinux/nut-upsd:latest is up-to-date
2024-12-04T18:10:38.549434599Z 04.12.2024 18:10:38 [info] Finished checking for image updates
2024-12-04T18:10:38.549519566Z 04.12.2024 18:10:38 [info] Next check in 5 minutes
2024-12-04T18:10:41.565943849Z 04.12.2024 18:10:41 [info] Image pulled successfully
2024-12-04T18:10:45.584697979Z 04.12.2024 18:10:45 [info] Checking for removed containers...
2024-12-04T18:10:45.599299531Z 04.12.2024 18:10:45 [info] Checking for containers...
2024-12-04T18:10:45.640623486Z 04.12.2024 18:10:45 [info] Finished checking for containers
2024-12-04T18:10:45.640708973Z 04.12.2024 18:10:45 [info] Next check in 5 minutes
2024-12-04T18:10:45.645670024Z 04.12.2024 18:10:45 [warn] Stopping MqDockerUp while updating containers: 4d029e10fdf7f977e23275de85b86f674b58f0884af0affbf031365f550e0da0
2024-12-04T18:10:45.661891800Z 04.12.2024 18:10:45 [error] Error during exit handling: Cannot read properties of undefined (reading 'Image')
2024-12-04T18:10:46.418612175Z
2024-12-04T18:10:46.418664778Z > mqdockerup@1.15.1 start
2024-12-04T18:10:46.418670139Z > ts-node src/index.ts
2024-12-04T18:10:46.418673968Z
2024-12-04T18:10:49.649442783Z 04.12.2024 18:10:49 [info]
2024-12-04T18:10:49.649478733Z   __  __       ____             _             _   _
2024-12-04T18:10:49.649483567Z  |  \/  | __ _|  _ \  ___   ___| | _____ _ __| | | |_ __
2024-12-04T18:10:49.649487552Z  | |\/| |/ _` | | | |/ _ \ / __| |/ / _ \ '__| | | | '_ \
2024-12-04T18:10:49.649491427Z  | |  | | (_| | |_| | (_) | (__|   <  __/ |  | |_| | |_) |
2024-12-04T18:10:49.649495486Z  |_|  |_|\__, |____/ \___/ \___|_|\_\___|_|   \___/| .__/
2024-12-04T18:10:49.649499828Z             |_|                                    |_|
2024-12-04T18:10:49.649503479Z Starting MqDockerUp V1.15.1 ...
2024-12-04T18:10:49.649507333Z
2024-12-04T18:10:50.351566807Z 04.12.2024 18:10:50 [info] Connected to the database.
2024-12-04T18:10:50.371637512Z 04.12.2024 18:10:50 [info] MQTT client successfully connected
2024-12-04T18:10:50.372199433Z 04.12.2024 18:10:50 [info] Checking for removed containers...
2024-12-04T18:10:50.379699689Z 04.12.2024 18:10:50 [info] Database initialized successfully
2024-12-04T18:10:50.401562963Z 04.12.2024 18:10:50 [info] Checking for containers...
2024-12-04T18:10:50.407287192Z 04.12.2024 18:10:50 [info] Removed missing container 72d7f1755bca_duplicati from Home Assistant and database.
```

**Comment by marleyjaffe** [comment]
I am experiencing the same issue. After updating a container using the Home-Assistant Update functionality, the mqdockerup container stops and the newly updated container does no auto start backup, instead the image gets updated but the container stops and does not restart.

**Comment by JackTalisker** [comment]
Even with latest release mqdockerup stops with further detalis:
![Screenshot 2024-12-21 093634](https://github.com/user-attachments/assets/213dc494-8427-44a8-a54a-24f2a8924d8b)

**Comment by SiriosDev** [comment]
It's a problem with the container mentioned in the warning, have you deleted any containers recently?

**Comment by JackTalisker** [comment]
Maybe a couple of weeks ago when mqdockerup stopped for the first time I had to manually make some clean up since that container (duplicati) was giving problems even by manual install.

**Comment by JackTalisker** [comment]
Happened again while trying to update another container.

```

2024-12-23T06:32:15.806045487Z 23.12.2024 06:32:15 [info] Checking for removed containers...
2024-12-23T06:32:15.859718466Z 23.12.2024 06:32:15 [warn] Stopping MqDockerUp while updating containers: 24561adba65a4666fbf8c11e1c4aa543bbec4f7ee4c7d7236fb0d67913324c52
2024-12-23T06:32:15.861778379Z 23.12.2024 06:32:15 [error] MqDockerUp stopped due to an error
2024-12-23T06:32:15.862294356Z 23.12.2024 06:32:15 [error] object
2024-12-23T06:32:15.870592454Z 23.12.2024 06:32:15 [error] Error: (HTTP code 404) no such container - No such container: 24561adba65a4666fbf8c11e1c4aa543bbec4f7ee4c7d7236fb0d67913324c52
2024-12-23T06:32:15.870659279Z     at /app/node_modules/docker-modem/lib/modem.js:382:17
2024-12-23T06:32:15.870668366Z     at getCause (/app/node_modules/docker-modem/lib/modem.js:417:7)
2024-12-23T06:32:15.870675091Z     at Modem.buildPayload (/app/node_modules/docker-modem/lib/modem.js:378:5)
2024-12-23T06:32:15.870681128Z     at IncomingMessage.<anonymous> (/app/node_modules/docker-modem/lib/modem.js:346:16)
2024-12-23T06:32:15.870687338Z     at IncomingMessage.emit (node:events:529:35)
2024-12-23T06:32:15.870693064Z     at IncomingMessage.emit (node:domain:489:12)
2024-12-23T06:32:15.870699073Z     at endReadableNT (node:internal/streams/readable:1400:12)
2024-12-23T06:32:15.870704781Z     at processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-12-23T06:32:16.675461584Z
2024-12-23T06:32:16.675510443Z > mqdockerup@1.15.2 start
2024-12-23T06:32:16.675515627Z > ts-node src/index.ts
2024-12-23T06:32:16.675519419Z
2024-12-23T06:32:19.910823153Z 23.12.2024 06:32:19 [info]
2024-12-23T06:32:19.910858637Z   __  __       ____             _             _   _
2024-12-23T06:32:19.910863201Z  |  \/  | __ _|  _ \  ___   ___| | _____ _ __| | | |_ __
2024-12-23T06:32:19.910867142Z  | |\/| |/ _` | | | |/ _ \ / __| |/ / _ \ '__| | | | '_ \
2024-12-23T06:32:19.910870750Z  | |  | | (_| | |_| | (_) | (__|   <  __/ |  | |_| | |_) |
2024-12-23T06:32:19.910874142Z  |_|  |_|\__, |____/ \___/ \___|_|\_\___|_|   \___/| .__/

```
