### ISSUE TITLE
MqDockerUp stopped due to an error

### ISSUE THREAD

**Issue by chriswood1001** [MichelFR/MqDockerUp#68]
The container appears to be in an endless restart approximately every minute. 

I'm running V0.16.2.

```
2023-05-25T02:30:31.506732761Z 25.05.2023 02:30:31 [info] 	Finished checking for image updates
2023-05-25T02:30:31.507198747Z 25.05.2023 02:30:31 [info] 	Next check in 5 minutes
2023-05-25T02:30:36.969450468Z 25.05.2023 02:30:36 [error] 	MqDockerUp stopped due to an error
2023-05-25T02:30:36.969616858Z 25.05.2023 02:30:36 [error] 	object
2023-05-25T02:30:36.977221950Z 25.05.2023 02:30:36 [error] 	SyntaxError: Unexpected end of JSON input
2023-05-25T02:30:36.977240122Z     at JSON.parse (<anonymous>)
2023-05-25T02:30:36.977243174Z     at /app/src/index.ts:48:21
2023-05-25T02:30:36.977245454Z     at Generator.next (<anonymous>)
2023-05-25T02:30:36.977247740Z     at /app/dist/src/index.js:8:71
2023-05-25T02:30:36.977249681Z     at new Promise (<anonymous>)
2023-05-25T02:30:36.977251596Z     at __awaiter (/app/dist/src/index.js:4:12)
2023-05-25T02:30:36.977253489Z     at MqttClient.<anonymous> (/app/src/index.ts:47:60)
2023-05-25T02:30:36.977255445Z     at MqttClient.emit (node:events:511:28)
2023-05-25T02:30:36.977257358Z     at MqttClient._handlePublish (/app/node_modules/mqtt/lib/client.js:1547:12)
2023-05-25T02:30:36.977259409Z     at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:535:12)
2023-05-25T02:30:37.916465879Z 
2023-05-25T02:30:37.916490301Z > mqdockerup@0.16.2 start
2023-05-25T02:30:37.916494804Z > node dist/src/index.js
```

**Comment by MichelFR** [comment]
That's because there are some messages being sent in MQTT which are not formatted as JSON.

I'll make it compatible to that by ignoring those values, that should fix it.

I'm gonna use this issue to track the progress. Thanks for bringing this to my attention.

**Comment by knorrre** [comment]
Same problem here. Is there a solution yet?

**Comment by MichelFR** [comment]
Should be fixed in next release

**Comment by chriswood1001** [comment]
The error is now reporting as a graceful warning. Critical issue resolved.

Is there a way to determine what JSON input is failing as my logs are flooded with this now. It's unclear what's needed to rectify.

**Comment by MichelFR** [comment]
The only thing you could do is to subscribe to the MQTT  yourself and check which data is beeing sent there.
In Future im gonna rewrite some logic, so that i wont listen to it at all.
