### ISSUE TITLE
Error launching after update. Cannot read properties of undefined (reading 'dockerhub')

### ISSUE THREAD

**Issue by chriswood1001** [MichelFR/MqDockerUp#94]
I receive the below error when launching my MqDockerUp container. Testing version 1.0.2 exhibits the same, while 1.0.1 runs with a "TypeError: Cannot read properties of undefined (reading 'split')" warning, but otherwise appears to work.

When reverting back to 0.16.4 the system runs as expected.

My docker compose references the config.yaml file that's identical to the documentation, but with my own values.

```
Starting MqDockerUp V1.0.3 ... 

TypeError: Cannot read properties of undefined (reading 'dockerhub')
    at ConfigService.getConfig (/app/dist/src/services/ConfigService.js:48:152)
    at Object.<anonymous> (/app/dist/src/services/HomeassistantService.js:18:40)
    at Module._compile (node:internal/modules/cjs/loader:1257:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1115:32)
    at Module._load (node:internal/modules/cjs/loader:962:12)
    at Module.require (node:internal/modules/cjs/loader:1139:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (/app/dist/src/index.js:18:48)
    at Module._compile (node:internal/modules/cjs/loader:1257:14)
TypeError: Cannot read properties of undefined (reading 'dockerhub')
    at Function.getConfig (/app/src/services/ConfigService.ts:47:107)
    at Object.<anonymous> (/app/src/index.ts:9:30)
    at Module._compile (node:internal/modules/cjs/loader:1257:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1115:32)
    at Function.Module._load (node:internal/modules/cjs/loader:962:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47
/app/src/index.ts:10
const client = mqtt.connect(config.mqtt.connectionUri, {
                                   ^
TypeError: Cannot read properties of undefined (reading 'mqtt')
    at Object.<anonymous> (/app/src/index.ts:10:36)
    at Module._compile (node:internal/modules/cjs/loader:1257:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1115:32)
    at Function.Module._load (node:internal/modules/cjs/loader:962:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
```

**Comment by MichelFR** [comment]
Please make sure you have the following config structure:
https://[raw.githubusercontent.com/MichelFR/MqDockerUp/main/config.yaml](https://raw.githubusercontent.com/MichelFR/MqDockerUp/main/config.yaml)

Dont forget

```
accessTokens:
  dockerhub:
  github:
```
  
  even if you dont want to set an accessToken

**Comment by chriswood1001** [comment]
Ah, that solved it. 

I had presumed those accessTokens were only necessary if you actually had them. Thank you.
